import os
import ast
import pickle
import numpy as np
import pandas as pd
import argparse
import matplotlib.pyplot as plt

class File_selection(object):
    def __init__(self, dictionary_of_names, languages, debug = False):
        self.dictionary_of_names = dictionary_of_names
        self.people = self.read_people()
        self.languages = self.select_languages(languages)
        self.selected_people = self.find_selected_languages(self.languages)
        if debug:
            self.all_languages = self.find_languages()
            self.acronims, self.values, self.quantities = self.find_language_quantities()
            self.generate_table()
            self.plot_quantities(20)

    def read_people(self):
        people = {}
        counter = 1
        for l in os.listdir(self.dictionary_of_names):
            if 'dictionary_of_names' in l:
                file = open(self.dictionary_of_names + l,'r')
                for i in file:
                    if len(i) > 2:
                        t = ast.literal_eval(i)
                        if type(t) is not float:
                            people[t[2]] = t[3]
                        else:
                            print('reading dictionaries files... ', counter)
                            counter +=  1
        return people

    def find_selected_languages(self, languages):
        selected_people = {}
        for k, v in self.people.items():
            selected_languages = []
            if v:
                for lan in v:                    
                    if lan[0] in languages:
                        selected_languages.append(lan)
                if len(selected_languages) == len(languages):
                    selected_people[k] = selected_languages
        return selected_people

    def select_languages(self, languages):
        selected_languages = []
        if not languages:
            selected_languages = self.find_languages()
        else:
            selected_languages = languages
        return selected_languages

    def find_languages(self):
        languages_acronim = []
        for k,v in self.people.items():
            if v:
                for lan in v:
                    if lan[0] not in languages_acronim:
                        languages_acronim.append(lan[0])
        return languages_acronim

    def find_language_quantities(self):
        num_languages = []
        for acronim in self.all_languages:
            if len(acronim) < 5:
                num_languages.append([int(len(self.find_selected_languages([acronim]))), acronim])
        num_languages.sort(reverse = True)
        num_languages = np.array(num_languages)
        values = num_languages[:,0].astype(int)
        acronims = num_languages[:,1]
        return acronims, values, num_languages

    def plot_quantities(self, num_languages):
        plt.rcdefaults()
        fig, ax = plt.subplots()
        y_pos = np.arange(num_languages)
        error = np.random.rand(num_languages)
        ax.barh(y_pos, self.values[:num_languages], xerr=error, align='center', color='gray')
        ax.tick_params(direction='out', length=6, width=2, labelsize='28',
               grid_color='r', grid_alpha=0.5)
        ax.set_yticks(y_pos)
        ax.set_ylabel('Languages', fontsize=28, position=(1.0, 0.5))
        ax.set_xlabel('Wikipedia entries', fontsize=28)
        ax.set_yticklabels(self.acronims[:num_languages])
        ax.invert_yaxis()  # labels read top-to-bottom

    def generate_table(self):
        f = open("plots/table", "w")
        f.write(pd.DataFrame.to_latex(pd.DataFrame(self.quantities)))
        f.close()

    def store(self, save_path):
        with open(save_path, 'wb') as f:
            pickle.dump(self.selected_people, f)

def retrieve_args():
    parser = argparse.ArgumentParser(description='Generates a pickle in which contains the dictionary of the samples in which all languages have the same entry')
    parser.add_argument('-l','--languages', nargs='+', help='Languages in which the lists will be generated', default='')
    parser.add_argument('-f','--folder', help='Folder in which the dictionaries generated by wp_api_language_search are stored', default='dictionary_of_names/')
    parser.add_argument('-s','--save_path', required=False, help='Store the class in a pickle, which will be used on the corpus_alignment module', default='files_selected.pickle')
    parser.add_argument('-d', '--debug', default=False, action='store_true')
    args = parser.parse_args()
    return args

def main():
    args = retrieve_args()
    languages = args.languages
    dictionary_of_names = args.folder
    save_path = args.save_path
    debug = args.debug
    file_selection = File_selection(dictionary_of_names, languages, debug = debug)
    file_selection.store(save_path)

if __name__ == '__main__':
    main()

